// Code generated by god. DO NOT EDIT.
package types

type BannerFindBannerListItem struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	ImageUrl   string `json:"imageUrl"`
	TargetUrl  string `json:"targetUrl"`
	PageUrl    string `json:"pageUrl"`
	SortNo     int64  `json:"sortNo"`
	Type       int64  `json:"type"`
	IsAble     int64  `json:"isAble"`
	OptId      string `json:"optId"`
	OptName    string `json:"optName"`
	CreateTime int64  `json:"createTime"`
	UpdateTime int64  `json:"updateTime"`
}

type BannerFindBannerListReq struct {
	Type int64 `json:"type"`
}

type FindMemorialFeteHomePageReq struct {
	Id int64 `json:"id"`
}

type FindMemorialFeteHomePageResp struct {
	Hudie               []string      `json:"hudie"`
	Pinyao              []string      `json:"pinyao"`
	Peiji               []string      `json:"peiji"`
	Xianheshengui       []string      `json:"xianheshengui"`
	Saomu               []string      `json:"saomu"`
	Xianhuabsdz         []string      `json:"xianhuabsdz"`
	Lazhu               []string      `json:"lazhu"`
	Chajiu              []string      `json:"chajiu"`
	Jibai               []string      `json:"jibai"`
	Bianpao             []string      `json:"bianpao"`
	Guangyun            []string      `json:"guangyun"`
	Xianglu             []string      `json:"xianglu"`
	Saomubsdz           []string      `json:"saomubsdz"`
	BianpaoMusic        []string      `json:"bianpaoMusic"`
	Xianhua             []string      `json:"xianhua"`
	UserFeteList        []string      `json:"userFeteList"`
	BackgroundMusicName string        `json:"backgroundMusicName"`
	BackgroundMusicUrl  string        `json:"backgroundMusicUrl"`
	MemorialInfo        *MemorialInfo `json:"memorialInfo"`
}

type FindPlatformDetailsReq struct {
}

type FindPlatformDetailsResp struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	Label      string `json:"label"`
	Mobile     string `json:"mobile"`
	CreateTime int64  `json:"createTime"`
	Enterprise string `json:"enterprise"`
	MobileDesc string `json:"mobileDesc"`
	UpdateTime int64  `json:"updateTime"`
	VisitCount int64  `json:"visitCount"`
}

type FindPlatformEnterpriseDetailReq struct {
}

type FindPlatformEnterpriseDetailResp struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	OptId        string `json:"optId"`
	CreateTime   int64  `json:"createTime"`
	PlatformId   string `json:"platformId"`
	UpdateTime   int64  `json:"updateTime"`
	Description  string `json:"description"`
	PlatformName string `json:"platformName"`
}

type FindPlatformMemorialConfigDetailReq struct {
	Id string `json:"id"`
}

type FindPlatformMemorialConfigItem struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	OptId           string `json:"optId"`
	OptName         string `json:"optName"`
	IsAble          int64  `json:"isAble"`
	HeadImage       string `json:"headImage"`
	CreateTime      int64  `json:"createTime"`
	PlatformId      string `json:"platformId"`
	UpdateTime      int64  `json:"updateTime"`
	BackgroundImage string `json:"backgroundImage"`
	NameOne         string `json:"nameOne"`
	NameTwo         string `json:"nameTwo"`
	RelationOne     string `json:"relationOne"`
	RelationTwo     string `json:"relationTwo"`
}

type FindSystemFeteSceneItem struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	OptId         string `json:"optId"`
	OptName       string `json:"optName"`
	SortNo        int64  `json:"sortNo"`
	ImageUrl      string `json:"imageUrl"`
	MusicUrl      string `json:"musicUrl"`
	ObjectId      string `json:"objectId"`
	SceneType     string `json:"sceneType"`
	CreateTime    int64  `json:"createTime"`
	ObjectType    string `json:"objectType"`
	PreviewUrl    string `json:"previewUrl"`
	UpdateTime    int64  `json:"updateTime"`
	SceneTypeName string `json:"sceneTypeName"`
}

type FindSystemFeteSceneReq struct {
}

type FindSystemFeteSceneResp struct {
	Hudie           []*FindSystemFeteSceneItem `json:"hudie,omitempty"`
	Lazhu           []*FindSystemFeteSceneItem `json:"lazhu,omitempty"`
	Muhua           []*FindSystemFeteSceneItem `json:"muhua,omitempty"`
	Saomu           []*FindSystemFeteSceneItem `json:"saomu,omitempty"`
	Guibai          []*FindSystemFeteSceneItem `json:"guibai,omitempty"`
	Rahmen          []*FindSystemFeteSceneItem `json:"rahmen,omitempty"`
	Xianhe          []*FindSystemFeteSceneItem `json:"xianhe,omitempty"`
	Bianpao         []*FindSystemFeteSceneItem `json:"bianpao,omitempty"`
	Message         []*FindSystemFeteSceneItem `json:"message,omitempty"`
	Xianglu         []*FindSystemFeteSceneItem `json:"xianglu,omitempty"`
	Xianhua         []*FindSystemFeteSceneItem `json:"xianhua,omitempty"`
	Guangyun        []*FindSystemFeteSceneItem `json:"guangyun,omitempty"`
	Bianpaomusic    []*FindSystemFeteSceneItem `json:"bianpaomusic,omitempty"`
	Yindaofooter    []*FindSystemFeteSceneItem `json:"yindaofooter,omitempty"`
	Yindaoheader    []*FindSystemFeteSceneItem `json:"yindaoheader,omitempty"`
	Xianheshengui   []*FindSystemFeteSceneItem `json:"xianheshengui,omitempty"`
	Jianguanfooter  []*FindSystemFeteSceneItem `json:"jianguanfooter,omitempty"`
	Jianguanheader  []*FindSystemFeteSceneItem `json:"jianguanheader,omitempty"`
	Backgroundimage []*FindSystemFeteSceneItem `json:"backgroundimage,omitempty"`
	Backgroundmusic []*FindSystemFeteSceneItem `json:"backgroundmusic,omitempty"`
	Peiji           []*FindSystemFeteSceneItem `json:"peiji,omitempty"`
	Daonian         []*FindSystemFeteSceneItem `json:"daonian,omitempty"`
	Pingdao         []*FindSystemFeteSceneItem `json:"pingdao,omitempty"`
	Jingxiang       []*FindSystemFeteSceneItem `json:"jingxiang,omitempty"`
}

type GetMemorialFormReq struct {
	Id int64 `json:"id"`
}

type GrjResp struct {
	Code       int64       `json:"code"`
	Data       interface{} `json:"data"`
	Count      int64       `json:"count"`
	TotalValue int64       `json:"totalValue"`
	TotalInfo  interface{} `json:"totalInfo"`
}

type LogReq struct {
	Id        int64  `json:"id"`
	Page      string `json:"p"`
	Params    string `json:"ps"`
	Action    string `json:"act"`
	StartTime int64  `json:"st"`
	EndTime   int64  `json:"et"`
}

type LoginReq struct {
	Code string `json:"code"`
}

type LoginResp struct {
	UserId   int64  `json:"userId"`
	Token    string `json:"token"`
	SellerId int64  `json:"sellerId"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
}

type MemorialFindTopMemorialListItem struct {
	Id                  string `json:"id"`
	MemorialNo          string `json:"memorialNo"`
	CloudMemorialNo     string `json:"cloudMemorialNo"`
	HeadImageUrl        string `json:"headImageUrl"`
	DefaultHeadImageUrl string `json:"defaultHeadImageUrl"`
	Homepage            string `json:"homepage"`
	Name                string `json:"name"`
	Relation            string `json:"relation"`
	Prefix              string `json:"prefix"`
	VisitCount          int64  `json:"visitCount"`
	Type                string `json:"type"`
	Title               string `json:"title"`
	Description         string `json:"description"`
	Label               string `json:"label"`
	SortNo              int64  `json:"sortNo"`
	IsReward            int64  `json:"isReward"`
	CreateTime          int64  `json:"createTime"`
	UpdateTime          int64  `json:"updateTime"`
}

type MemorialForm struct {
	HeadImg     string `json:"headImg"`
	NameOne     string `json:"nameOne"`
	NameTwo     string `json:"nameTwo"`
	RelationOne string `json:"relationOne"`
	RelationTwo string `json:"relationTwo"`
	VisitCount  int64  `json:"visitCount"`
}

type MemorialInfo struct {
	Id                     int64  `json:"id"`
	MemorialNo             string `json:"memorialNo"`
	HeadImg                string `json:"headImg"`
	DefaultHeadImg         string `json:"defaultHeadImg"`
	Rahmen                 string `json:"rahmen"`
	Homepage               string `json:"homepage"`
	BackgroundMusic        string `json:"backgroundMusic"`
	JntBackgroundMusic     string `json:"jntBackgroundMusic"`
	WltBackgroundMusic     string `json:"wltBackgroundMusic"`
	QftBackgroundMusic     string `json:"qftBackgroundMusic"`
	BackgroundMusicName    string `json:"backgroundMusicName"`
	JntBackgroundMusicName string `json:"jntBackgroundMusicName"`
	WltBackgroundMusicName string `json:"wltBackgroundMusicName"`
	QftBackgroundMusicName string `json:"qftBackgroundMusicName"`
	Name                   string `json:"name"`
	Relation               string `json:"relation"`
	Birthdate              string `json:"birthdate"`
	Deathdate              string `json:"deathdate"`
	Remark                 string `json:"remark"`
	Blog                   string `json:"blog"`
	JntBackgroundImage     string `json:"jntBackgroundImage"`
	WltBackgroundImage     string `json:"wltBackgroundImage"`
	QftBackgroundImage     string `json:"qftBackgroundImage"`
}

type PostMemorialFormResp struct {
	Id int64 `json:"id"`
}

type QiniuTokenReq struct {
	Bucket int64 `json:"bucket" v:"required|min:1#bucket不得为空|bucket不得为空"`
}
